# Generated by Django 2.1.7 on 2019-02-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190224_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebook',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='ebook',
            name='source',
            field=models.CharField(choices=[('1', 'GitHub'), ('2', 'Google'), ('3', 'Direct')], default='2', max_length=1),
            preserve_default=False,
        ),
    ]
